# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(11, 11, 279, 55))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 22, 251, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.com_selector = QtWidgets.QComboBox(self.widget)
        self.com_selector.setObjectName("com_selector")
        self.horizontalLayout_5.addWidget(self.com_selector)
        self.baud_selector = QtWidgets.QComboBox(self.widget)
        self.baud_selector.setObjectName("baud_selector")
        self.baud_selector.addItem("")
        self.baud_selector.addItem("")
        self.baud_selector.addItem("")
        self.baud_selector.addItem("")
        self.horizontalLayout_5.addWidget(self.baud_selector)
        self.com_btn = QtWidgets.QPushButton(self.widget)
        self.com_btn.setAutoFillBackground(True)
        self.com_btn.setObjectName("com_btn")
        self.horizontalLayout_5.addWidget(self.com_btn)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(11, 72, 281, 231))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget1 = QtWidgets.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 251, 191))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.check_r1 = QtWidgets.QCheckBox(self.widget1)
        self.check_r1.setChecked(True)
        self.check_r1.setObjectName("check_r1")
        self.horizontalLayout.addWidget(self.check_r1)
        self.check_r2 = QtWidgets.QCheckBox(self.widget1)
        self.check_r2.setObjectName("check_r2")
        self.horizontalLayout.addWidget(self.check_r2)
        self.check_r3 = QtWidgets.QCheckBox(self.widget1)
        self.check_r3.setObjectName("check_r3")
        self.horizontalLayout.addWidget(self.check_r3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gain_selector = QtWidgets.QComboBox(self.widget1)
        self.gain_selector.setObjectName("gain_selector")
        self.horizontalLayout_2.addWidget(self.gain_selector)
        self.check_2_5g = QtWidgets.QRadioButton(self.widget1)
        self.check_2_5g.setChecked(False)
        self.check_2_5g.setObjectName("check_2_5g")
        self.horizontalLayout_2.addWidget(self.check_2_5g)
        self.check_5g = QtWidgets.QRadioButton(self.widget1)
        self.check_5g.setChecked(True)
        self.check_5g.setObjectName("check_5g")
        self.horizontalLayout_2.addWidget(self.check_5g)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jz_plus_btn = QtWidgets.QPushButton(self.widget1)
        self.jz_plus_btn.setObjectName("jz_plus_btn")
        self.horizontalLayout_3.addWidget(self.jz_plus_btn)
        self.jz_plus_ipt = QtWidgets.QLineEdit(self.widget1)
        self.jz_plus_ipt.setObjectName("jz_plus_ipt")
        self.horizontalLayout_3.addWidget(self.jz_plus_ipt)
        self.jz_minus_btn = QtWidgets.QPushButton(self.widget1)
        self.jz_minus_btn.setObjectName("jz_minus_btn")
        self.horizontalLayout_3.addWidget(self.jz_minus_btn)
        self.jz_minus_ipt = QtWidgets.QLineEdit(self.widget1)
        self.jz_minus_ipt.setObjectName("jz_minus_ipt")
        self.horizontalLayout_3.addWidget(self.jz_minus_ipt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.delay_btn = QtWidgets.QPushButton(self.widget1)
        self.delay_btn.setObjectName("delay_btn")
        self.horizontalLayout_4.addWidget(self.delay_btn)
        self.delay_ipt = QtWidgets.QLineEdit(self.widget1)
        self.delay_ipt.setObjectName("delay_ipt")
        self.horizontalLayout_4.addWidget(self.delay_ipt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 10, 631, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.figure_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.figure_layout.setContentsMargins(0, 0, 0, 0)
        self.figure_layout.setObjectName("figure_layout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.baud_selector.setItemText(0, _translate("MainWindow", "9600"))
        self.baud_selector.setItemText(1, _translate("MainWindow", "38400"))
        self.baud_selector.setItemText(2, _translate("MainWindow", "115200"))
        self.baud_selector.setItemText(3, _translate("MainWindow", "921600"))
        self.com_btn.setText(_translate("MainWindow", "打开串口"))
        self.label.setText(_translate("MainWindow", "通道:"))
        self.check_r1.setText(_translate("MainWindow", "R1"))
        self.check_r2.setText(_translate("MainWindow", "R2"))
        self.check_r3.setText(_translate("MainWindow", "R3"))
        self.label_2.setText(_translate("MainWindow", "增益:"))
        self.check_2_5g.setText(_translate("MainWindow", "2.5G"))
        self.check_5g.setText(_translate("MainWindow", "5G"))
        self.jz_plus_btn.setText(_translate("MainWindow", "校准+"))
        self.jz_minus_btn.setText(_translate("MainWindow", "校准-"))
        self.delay_btn.setText(_translate("MainWindow", "延时"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "常用设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "更多设置"))

